const Data = [
  {
    id: "1",
    name: "nacklace",
    shortDescription: "nice quality necklace",
    decription: "you can tru our nice quality necklace",
    price: 200000,
    imgSrcUrl: "images/Birds-of-Paradise-Pendant-1-325x325.jpg",
  },
  {
    id: "2",
    name: "nacklace",
    shortDescription: "nice quality necklace",
    decription: "you can tru our nice quality necklace",
    price: 200000,
    imgSrcUrl: "images/Cross-of-Light-Pendant-1-325x325.jpg",
  },
  {
    id: "3",
    name: "ring",
    shortDescription: "nice quality necklace",
    decription: "you can tru our nice quality necklace",
    price: 200000,
    imgSrcUrl: "images/Cross-Stripes-Stone-Bracelet-1-325x325.jpg",
  },
  {
    id: "4",
    name: "pendant",
    shortDescription: "nice quality necklace",
    decription: "you can tru our nice quality necklace",
    price: 200000,
    imgSrcUrl: "images/Echoes-Necklace-Extension-Piece-1-325x325.jpg",
  },
  {
    id: "5",
    name: "nacklace",
    shortDescription: "nice quality necklace",
    decription: "you can tru our nice quality necklace",
    price: 200000,
    imgSrcUrl: "images/Four-Leaf-Clover-Rings-1-325x325.jpg",
  },
  {
    id: "6",
    name: "nacklace",
    shortDescription: "nice quality necklace",
    decription: "you can tru our nice quality necklace",
    price: 200000,
    imgSrcUrl: "images/Blue-Stripes-Stone-Earrings-1-325x325.jpg",
  },
  {
    id: "7",
    name: "nacklace",
    shortDescription: "nice quality necklace",
    decription: "you can tru our nice quality necklace",
    price: 200000,
    imgSrcUrl: "images/Kalvesna-Diamond-Twig-Ring-1-325x325.jpg",
  },
  {
    id: "8",
    name: "nacklace",
    shortDescription: "nice quality necklace",
    decription: "you can tru our nice quality necklace",
    price: 200000,
    imgSrcUrl: "images/Circle-of-Light-Heart-Earrings-1-325x325.jpg",
  },
  {
    id: "9",
    name: "nacklace",
    shortDescription: "nice quality necklace",
    decription: "you can tru our nice quality necklace",
    price: 200000,
    imgSrcUrl: "images/Birds-of-Paradise-Pendant-1-325x325.jpg",
  },
  {
    id: "10",
    name: "nacklace",
    shortDescription: "nice quality necklace",
    decription: "you can tru our nice quality necklace",
    price: 200000,
    imgSrcUrl: "images/Birds-of-Paradise-Pendant-1-325x325.jpg",
  },
];

export default Data;
